### ISSUE TITLE
Unclear how to specify AWS credentials

### ISSUE THREAD

**Issue by brianreeve** [binoculars/aws-lambda-ffmpeg#16]
I tried following the README, but it is a little unclear how I specify my AWS credentials.

When running gulp, I am getting `Getting `TimeoutError: Missing credentials in config` in `aws:upload` and `aws:build-upload`.

I have set the proper bucket names in `aws/config.json`, but it's not clear by the docs how to specify my AWS credentials to proceed.

Is there a prerequisite or missing piece in the docs? Any clarification would be helpful.

**Comment by binoculars** [comment]
I covered it in the [this section of the README](/binoculars/aws-lambda-ffmpeg/blob/master/README.md#example-local-testing-script), but it's the same process for [configuring the AWS SDK for Node.js](https://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html). You either specify the environment variables, or with the AWS CLI, run `aws configure` to get it set up to load automatically. You'll also need to specify the `AWS_REGION` environment variable separately. I have mine set in my shell configuration to just set it to us-east-1 by default.

**Comment by brianreeve** [comment]
Makes sense now! Thanks.

Will be able to retry in a couple hours.
