### ISSUE TITLE
How to get ffmpeg on the lambda server

### ISSUE THREAD

**Issue by mayuresh-halshikar** [binoculars/aws-lambda-ffmpeg#17]
I am using java8 platform to code our lambdas. I want to use ffmpeg. How can I get ffmpeg on the server, my lambda code is running on.

**Comment by binoculars** [comment]
I would recommend using Node.js for this specific Lambda function. I am not familiar with how Java is used to call external binaries, or if there are Java bindings for FFmpeg. I'm not a Java developer. I would suggest taking a look at the [AWS Documentation for Creating a Deployment Package (Java)](https://docs.aws.amazon.com/lambda/latest/dg/lambda-java-how-to-create-deployment-package.html).
