### ISSUE TITLE
'untar-ffmpeg' fails with "Unrecognized archive format"

### ISSUE THREAD

**Issue by jjmaxwell4** [binoculars/aws-lambda-ffmpeg#19]
I recently upgraded to Mac OSx Version 10.11.6, and now when I try and run 

> `gulp aws:default`

I get the following error log:

> [15:51:25] Using gulpfile ~/XXXXXXXXXX
> [15:51:25] Starting 'aws:default'...
> [15:51:25] Starting 'aws:build-upload'...
> [15:51:25] Starting 'clean'...
> [15:51:26] Finished 'clean' after 13 ms
> [15:51:26] Starting 'download-ffmpeg'...
> [15:51:26] Starting 'aws:transpile'...
> [15:51:26] Starting 'aws:config'...
> [15:51:26] Starting 'npm'...
> [15:51:26] Finished 'aws:config' after 247 ms
> [15:51:26] Finished 'download-ffmpeg' after 268 ms
> [15:51:26] Finished 'aws:transpile' after 267 ms
> [15:51:26] Starting 'aws:source'...
> [15:51:26] Finished 'aws:source' after 2.35 μs
> [15:51:26] Finished 'npm' after 687 ms
> [15:51:26] Starting 'untar-ffmpeg'...
> tar: Unrecognized archive format
> tar: Error exit delayed from previous errors.
> [15:51:26] 'untar-ffmpeg' errored after 10 ms
> [15:51:26] Error: Command `tar -xvf build/ffmpeg-git-64bit-static.tar.xz -C ./build` failed with exit code 1
>     at ChildProcess.exithandler (child_process.js:202:12)
>     at emitTwo (events.js:100:13)
>     at ChildProcess.emit (events.js:185:7)
>     at maybeClose (internal/child_process.js:827:16)
>     at Socket.<anonymous> (internal/child_process.js:319:11)
>     at emitOne (events.js:90:13)
>     at Socket.emit (events.js:182:7)
>     at Pipe._onclose (net.js:475:12)
> [15:51:26] 'aws:default' errored after 730 ms
> [15:51:26] Error in plugin 'run-sequence(untar-ffmpeg)'
> Message:
>     Command `tar -xvf build/ffmpeg-git-64bit-static.tar.xz -C ./build` failed with exit code 1
> Details:
>     killed: false
>     code: 1
>     signal: null
>     cmd: tar -xvf build/ffmpeg-git-64bit-static.tar.xz -C ./build
>     stdout:
>     stderr: tar: Unrecognized archive format
> tar: Error exit delayed from previous errors.
> 
> Stack:
> Error: Command `tar -xvf build/ffmpeg-git-64bit-static.tar.xz -C ./build` failed with exit code 1
>     at ChildProcess.exithandler (child_process.js:202:12)
>     at emitTwo (events.js:100:13)
>     at ChildProcess.emit (events.js:185:7)
>     at maybeClose (internal/child_process.js:827:16)
>     at Socket.<anonymous> (internal/child_process.js:319:11)
>     at emitOne (events.js:90:13)
>     at Socket.emit (events.js:182:7)
>     at Pipe._onclose (net.js:475:12)
> [15:51:26] 'aws:build-upload' errored after 731 ms
> [15:51:26] Error in plugin 'run-sequence(aws:default)'
> Message:
>     Command `tar -xvf build/ffmpeg-git-64bit-static.tar.xz -C ./build` failed with exit code 1
> Details:
>     killed: false
>     code: 1
>     signal: null
>     cmd: tar -xvf build/ffmpeg-git-64bit-static.tar.xz -C ./build
>     stdout:
>     stderr: tar: Unrecognized archive format
> tar: Error exit delayed from previous errors.
> 
> Stack:
> Error: Command `tar -xvf build/ffmpeg-git-64bit-static.tar.xz -C ./build` failed with exit code 1
>     at ChildProcess.exithandler (child_process.js:202:12)
>     at emitTwo (events.js:100:13)
>     at ChildProcess.emit (events.js:185:7)
>     at maybeClose (internal/child_process.js:827:16)
>     at Socket.<anonymous> (internal/child_process.js:319:11)
>     at emitOne (events.js:90:13)
>     at Socket.emit (events.js:182:7)
>     at Pipe._onclose (net.js:475:12)
> [15:51:26] 'aws:build-upload' errored after 731 ms
> [15:51:26] Error in plugin 'run-sequence(untar-ffmpeg)'
> Message:
>     Command `tar -xvf build/ffmpeg-git-64bit-static.tar.xz -C ./build` failed with exit code 1
> Details:
>     killed: false
>     code: 1
>     signal: null
>     cmd: tar -xvf build/ffmpeg-git-64bit-static.tar.xz -C ./build
>     stdout:
>     stderr: tar: Unrecognized archive format
> tar: Error exit delayed from previous errors.
> 
> Stack:
> Error: Command `tar -xvf build/ffmpeg-git-64bit-static.tar.xz -C ./build` failed with exit code 1
>     at ChildProcess.exithandler (child_process.js:202:12)
>     at emitTwo (events.js:100:13)
>     at ChildProcess.emit (events.js:185:7)
>     at maybeClose (internal/child_process.js:827:16)
>     at Socket.<anonymous> (internal/child_process.js:319:11)
>     at emitOne (events.js:90:13)
>     at Socket.emit (events.js:182:7)
>     at Pipe._onclose (net.js:475:12)

It appears that the file that is getting downloaded from https://www.johnvansickle.com/ffmpeg/ is somehow getting corrupted.

Any ideas on how to debug?

**Comment by binoculars** [comment]
Apparently our friend @johnvansickle has implemented HTTPS on his site. The gulp task is currently using the old HTTP link.

```html

```
