### ISSUE TITLE
CloudFormation issue

### ISSUE THREAD

**Issue by gustavoserafim** [binoculars/aws-lambda-ffmpeg#22]
I'm getting the error below every time I'm running AWS:DEFAULT.
I set all full access permissions on IAM for my user to make sure it has the right permission to create whatever it needed but still.
 
CREATE_FAILED	AWS::IAM::Policy	ExecutionRolePolicy	Value of property Roles must be of type List of String

Any tip?

<img width="1141" alt="screenshot 2017-03-15 15 26 20" src="https://cloud.githubusercontent.com/assets/861963/23967051/e66e31e4-0993-11e7-89d3-a98abf3e3e38.png">

**Comment by binoculars** [comment]
Sorry, I screwed up the template for normal deployments. It's fixed now in v2.3.1, just pull the latest change.

**Comment by gustavoserafim** [comment]
Thanks!
CloudFormation worked ok now!
