### ISSUE TITLE
how to upload files for Azure

### ISSUE THREAD

**Issue by amoondra19** [binoculars/aws-lambda-ffmpeg#24]
Hi, 

I see that the gulpfile.js for Azure is empty and there are no tasks defined in that.

I have used your code with AWS and it works fine over there. But I can't use AWS as I need to transcode big files and in AWS lambda the max timeout is 5 mins and for transcoding it is taking more than that.

Could you please update the gulpfile for Azure? Or let me know how can it be done for Azure

**Comment by binoculars** [comment]
Hi @amoondra19 

I started working on using Azure (note the 'help wanted' in the README), but the main problem is that Azure functions run on Windows. We would need an FFmpeg executable for Windows to work. I currently don't have a build process in place for this. However, I would work with you and accept a pull request.

I think for your use case, Azure isn't the best option. I would recommend checking out [AWS Elastic Transcoder](https://aws.amazon.com/elastictranscoder/details/).

**Comment by amoondra19** [comment]
Hi,

Sure I'll do a pull. AWS Elastic transcoder might not work for me as the transcoding profiles will vary vastly in my case.

I am trying with GCP as it provides more RAM than AWS and more timeout limit. I have done gulp gcp:build and then uploaded the dist.zip file to Cloud functions. There when I am deploying the function I get the below error message.

"Function load error: File index.js or function.js that is expected to define function doesn't exist in the root directory."

I have kept the name of the function as 'entryPoint' which is there in gcp/index.js.

Could you please let me know what I might be missing.

**Comment by binoculars** [comment]
I haven't touched GCP since the alpha, so there are probably a few changes that need to be addressed. Don't rely on GCP right now--plus it's still only in beta, so things may change slightly.
