### ISSUE TITLE
lodash._rescope dependancy

### ISSUE THREAD

**Issue by pieterdt** [binoculars/aws-lambda-ffmpeg#26]
Hi, while trying to get gulp aws:create-cfn-bucket running, I bump into an error:

```
module.exports = (arr, ...values) => {
                       ^^^

SyntaxError: Unexpected token ...
```

just installed everything on a clean MacOsX Sierra, any suggestions?

**Comment by binoculars** [comment]
I'm unable to reproduce that error. Did you configure the AWS SDK for JavaScript? If not, you can do the following:

```bash
# Replace env variables with your own
export AWS_ACCESS_KEY_ID=AKIDEXAMPLE
export AWS_SECRET_ACCESS_KEY=asdf83jadjfe4example
CFN_S3_BUCKET='my-test-bucket-random-string' gulp aws:create-cfn-bucket
```
