### ISSUE TITLE
Error with Installation (Access Denied)

### ISSUE THREAD

**Issue by jessica88888** [binoculars/aws-lambda-ffmpeg#35]
Dear Binoculars,

I'm new to Github, AWS, Lambda, CloudFormation, Linux and FFMPEG. I'm trying to get this working with AWS, but no luck on that, I keep on getting errors and most of them are Access Denied. I've tried the below. I believe I've done some mistake somewhere, but I'm unable to find the problem source. It might be AWS access key, bucket policy problem, npm or maybe config.json? 

`export AWS_ACCESS_KEY_ID=AKIDEXAMPLE
export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY
export AWS_REGION=us-east-1
export DESTINATION_BUCKET=destination-bucket
# Note that the following variable is single-quote escaped. Use $KEY_PREFIX to get the filename minus the extension.
export FFMPEG_ARGS=$'-c:a copy -vf scale=\'min(320\\,iw):-2\' -movflags +faststart -metadata description=http://my.site/$KEY_PREFIX.mp4 out.mp4 -vf thumbnail -vf scale=\'min(320\\,iw):-2\' -vframes 1 out.png'
export USE_GZIP=false
export MIME_TYPES='{"png":"image/png","mp4":"video/mp4"}'
export VIDEO_MAX_DURATION='30'
# Node version
nvm use 6.10 # This is subject to change
# Babel-node test script
node node_modules/babel-cli/bin/babel-node.js test/aws.js`

`[hello@localhost aws-lambda-ffmpeg]$ CFN_S3_BUCKET=lambda-testfunction gulp aws:create-cfn-bucket
[17:13:23] Using gulpfile ~/aws-lambda-ffmpeg/gulpfile.js
[17:13:23] Starting 'aws:create-cfn-bucket'...
{ AccessDenied: Access Denied
    at Request.extractError (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/services/s3.js:539:35)
    at Request.callListeners (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/request.js:671:14)
    at Request.transition (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/request.js:673:12)
    at Request.callListeners (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2017-04-24T21:13:25.352Z,
  requestId: 'xxxxxxxxxxxxxxxxx',
  extendedRequestId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 22.117309923917226 }
[17:13:25] Finished 'aws:create-cfn-bucket' after 1.67 s
`

May I know is there any video tutorial available for newbies? It would be great if you could guide me on this, thank you.

Best regards,
Jessica

**Comment by binoculars** [comment]
Hi, it looks like you might need to set up your AWS account and/or set your AWS Credentials. The credentials provided are just for example only. I would recommend installing the AWS CLI and use that the first time, because it will save your Access Key and Secret Key for you. More info:
* http://docs.aws.amazon.com/lambda/latest/dg/setup-awscli.html
* http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey

I haven't put together any videos about it, but that sounds like a good idea. Let me know if that helps.

**Comment by jessica88888** [comment]
Dear Binoculars,

These are the steps I've gone through:

1) Setup AWS users on IAM (AWS Management Console) with policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "sqs:*",
                "cloudformation:CreateStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:DescribeStackResources",
                "cloudformation:GetTemplate",
                "cloudformation:ValidateTemplate"
            ],
            "Resource": "*"
        }
    ]
}
```

2) Created 3 S3 buckets - all located at us-west-2 (on AWS Management Console): 
My cfn s3 bucket, My input bucket, My output bucket
(No bucket policy, copied CORS configuration from the previous created bucket on S3, didn't set permission for buckets, I think the default is private)
```
<!-- Sample policy -->
<CORSConfiguration>
	<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>GET</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
		<AllowedHeader>Authorization</AllowedHeader>
	</CORSRule>
</CORSConfiguration>

```

3) Installed AWS CLI, and using aws configure:

```
$ aws configure
AWS Access Key ID [None]: [My access key id]
AWS Secret Access Key [None]:[My access key]
Default region name [None]: us-west-2
Default output format [None]: enter
```

4) Installed node using nvm: V6.10

```
[hello@localhost aws-lambda-ffmpeg]$ node --version
v6.10.2
```

5) Cloned this repo

6) cd to the directory and ran npm install

7) Create your function code's storage location (or choose an existing one)
  (I'm not sure what does this line mean, but created a bucket on S3)

8) Update the platform-specific configuration JSON file (see below), and/or modify the code file for your purposes
 (Couldn't find AWS configuration JSON file in folder **config_samples**, maybe no need for AWS?)

9) Edit event/{platform}.json
```

{
	"Records": [
		{
			"eventVersion": "2.0",
			"eventSource": "aws:s3",
			"awsRegion": "us-west-2",
			"eventTime": "2015-04-09T00:00:00.000Z",
			"eventName": "ObjectCreated:Post",
			"userIdentity": {
				"principalId": "566531202354"
			},
			"requestParameters": {
				"sourceIPAddress": "10.0.0.1"
			},
			"responseElements": {
				"x-amz-request-id": "AAAAAAAAAAAAAAAA",
				"x-amz-id-2": "example+uvBeYL11YHRGvzOb5qQz7cwxh7AzPlE+zuM2zRN6vTvd/1Qe0TJpKPCvZBoO4dB0gqM="
			},
			"s3": {
				"s3SchemaVersion": "1.0",
				"configurationId": "ProcessUploads",
				"bucket": {
					"name": "[My input bucket]",
					"ownerIdentity": {
						"principalId": "[My aws account id]"
					},
					"arn": "arn:aws:s3:::[My input bucket]"
				},
				"object": {
					"key": "us-east-1%3A8ca8d677-aaaa-aaaa-aaaa-b75e887648ee/public/0524d7ce-aaaa-aaaa-aaaa-1f8cf05b3862.mp4",
					"size": 1000000,
					"eTag": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
				}
			}
		}
	]
}
```

10) Ran this:

```
# Environment variables
export AWS_ACCESS_KEY_ID=[My access key id]
export AWS_SECRET_ACCESS_KEY=[My access key]
export AWS_REGION=us-west-2
export DESTINATION_BUCKET=[My Output bucket]
# Note that the following variable is single-quote escaped. Use $KEY_PREFIX to get the filename minus the extension.
export FFMPEG_ARGS=$'-c:a copy -vf scale=\'min(320\\,iw):-2\' -movflags +faststart -metadata description=http://my.site/$KEY_PREFIX.mp4 out.mp4 -vf thumbnail -vf scale=\'min(320\\,iw):-2\' -vframes 1 out.png'
export USE_GZIP=false
export MIME_TYPES='{"png":"image/png","mp4":"video/mp4"}'
export VIDEO_MAX_DURATION='30'
# Node version
nvm use 6.10 # This is subject to change
# Babel-node test script
node node_modules/babel-cli/bin/babel-node.js test/aws.js
```

**Returned:** 

```
[hello@localhost aws-lambda-ffmpeg]$ export AWS_ACCESS_KEY_ID=[My access key id]
[hello@localhost aws-lambda-ffmpeg]$ export AWS_SECRET_ACCESS_KEY=[My access key]
[hello@localhost aws-lambda-ffmpeg]$ export AWS_REGION=us-west-2
[hello@localhost aws-lambda-ffmpeg]$ export DESTINATION_BUCKET=[My Output bucket]
[hello@localhost aws-lambda-ffmpeg]$ # Note that the following variable is single-quote escaped. Use $KEY_PREFIX to get the filename minus the extension.
[hello@localhost aws-lambda-ffmpeg]$ export FFMPEG_ARGS=$'-c:a copy -vf scale=\'min(320\\,iw):-2\' -movflags +faststart -metadata description=http://my.site/$KEY_PREFIX.mp4 out.mp4 -vf thumbnail -vf scale=\'min(320\\,iw):-2\' -vframes 1 out.png'
[hello@localhost aws-lambda-ffmpeg]$ export USE_GZIP=false
[hello@localhost aws-lambda-ffmpeg]$ export MIME_TYPES='{"png":"image/png","mp4":"video/mp4"}'
[hello@localhost aws-lambda-ffmpeg]$ export VIDEO_MAX_DURATION='30'
[hello@localhost aws-lambda-ffmpeg]$ # Node version
[hello@localhost aws-lambda-ffmpeg]$ nvm use 6.10 # This is subject to change
bash: nvm: command not found...
[hello@localhost aws-lambda-ffmpeg]$ # Babel-node test script
[hello@localhost aws-lambda-ffmpeg]$ node node_modules/babel-cli/bin/babel-node.js test/aws.js
Reading options from event:
{ Records: 
   [ { eventVersion: '2.0',
       eventSource: 'aws:s3',
       awsRegion: 'us-west-2',
       eventTime: '2015-04-09T00:00:00.000Z',
       eventName: 'ObjectCreated:Post',
       userIdentity: { principalId: '[My aws account id]' },
       requestParameters: { sourceIPAddress: '10.0.0.1' },
       responseElements: 
        { 'x-amz-request-id': 'AAAAAAAAAAAAAAAA',
          'x-amz-id-2': 'example+uvBeYL11YHRGvzOb5qQz7cwxh7AzPlE+zuM2zRN6vTvd/1Qe0TJpKPCvZBoO4dB0gqM=' },
       s3: 
        { s3SchemaVersion: '1.0',
          configurationId: 'ProcessUploads',
          bucket: 
           { name: '[My input bucket]',
             ownerIdentity: { principalId: '[My aws account id]' },
             arn: 'arn:aws:s3:::[My input bucket]' },
          object: 
           { key: 'us-east-1%3A8ca8d677-aaaa-aaaa-aaaa-b75e887648ee/public/0524d7ce-aaaa-aaaa-aaaa-1f8cf05b3862.mp4',
             size: 1000000,
             eTag: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' } } } ] }
Starting download: [My input bucket] / us-east-1:8ca8d677-aaaa-aaaa-aaaa-b75e887648ee/public/0524d7ce-aaaa-aaaa-aaaa-1f8cf05b3862.mp4
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/tmp/download'
    at Error (native)
```


11) Also ran this:

```
export CFN_S3_BUCKET=[My cfn s3 bucket]
export SOURCE_BUCKET=[My input bucket]
export DESTINATION_BUCKET=[My output bucket]
# Note that the following variable is single-quote escaped. Use $KEY_PREFIX to get the filename minus the extension.
export FFMPEG_ARGS=$'-c:a copy -vf scale=\'min(320\\,iw):-2\' -movflags +faststart -metadata description=http://my.site/$KEY_PREFIX.mp4 out.mp4 -vf thumbnail -vf scale=\'min(320\\,iw):-2\' -vframes 1 out.png'
export USE_GZIP=false # can be true or false
export MIME_TYPES='{"png":"image/png","mp4":"video/mp4"}' # must be a JSON object with "extension": "mimeType" as the key/value pairs
export VIDEO_MAX_DURATION='30' # must be a number
```
```[hello@localhost aws-lambda-ffmpeg]$ CFN_S3_BUCKET=[My cfn s3 bucket] gulp aws:create-cfn-bucket```

**Returned**

```
[12:32:51] Using gulpfile ~/aws-lambda-ffmpeg/gulpfile.js
[12:32:51] Starting 'aws:create-cfn-bucket'...
{ AccessDenied: Access Denied
    at Request.extractError (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/services/s3.js:539:35)
    at Request.callListeners (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/request.js:671:14)
    at Request.transition (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/request.js:673:12)
    at Request.callListeners (/home/hello/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2017-04-25T16:32:53.117Z,
  requestId: '56xxxxxxxxxxxxx6F',
  extendedRequestId: 'vowoxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxauHddAxxxxxxxxxx7+kxmxxxxxxxxxxBxxxxxxx9k=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 48.67479543747064 }
[12:32:53] Finished 'aws:create-cfn-bucket' after 1.2 s
```

I believe I've made lots of mistakes above, sorry for being dumb on all of these, I'm not familiar with the flows, it would be really great if you could help to point me out to set this correctly and securely on AWS, many thanks.

Best regards,
Jessica

**Comment by binoculars** [comment]
I would give your user admin access. CloudFormation isn't enough to create everything--it has to have access to everything CloudFormation creates. You can use the Administrator [AWS Managed Policy](http://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html#aws-managed-policies).

Also, you only need to create the CFN_S3_BUCKET. Skip running `gulp aws:create-cfn-bucket` if you already have this. The other 2 buckets for source and destination will be created when you create run `gulp aws:default`

I deprecated using `config.json` in favor of defining environment variables, since AWS Lambda now uses them.

**Comment by jessica88888** [comment]
Thank you so much, I finally got it running on AWS.

1) May I know what should I do, if I would like to convert into these formats:

MP4 360P
MP4 720p
WEBM 360P
WEBM 720P
THUMBNAIL PNG 360P
THUMBNAIL PNG720P

2) As you've mentioned in the readme : 

> This function is meant for short-duration videos. If you need to transcode long videos, check out AWS Elastic Transcoder.

If that's the case, may I know what is the maximum / recommended length of the video?

3) Is there any limitation video’s file size?

4) Will lambda retry when it fails? Is there any possibility of updating Mysql DB with PHP on the status of transcoding like Success / Processing / Error?

5) Would it be possible to delete the original on successful transcoding?

Thanks Binoculars.

**Comment by binoculars** [comment]
* See [Creating Multiple Outputs](https://trac.ffmpeg.org/wiki/Creating%20multiple%20outputs) in the FFmpeg documentation.
* Lambda has hard limits on disk space, however there may be workarounds for this--like mounting an EFS directory, but that's something I haven't tried yet. The /tmp directory has to be able to hold the input file, and all of the output files at once, so be mindful of that. I'd recommend keeping the videos under 256 MB, but if you're doing multiple outputs with one lambda function, it may need to go lower.
* AWS offers Dead Letter Queues for Lambda, so you could make something to handle failures using that. Usually, it will auto-retry 3 times if there is a failure.
* I wouldn't recommend deleting the original after successful transcoding. You probably want to send it to cold storage like Glacier or use S3 infrequent access. If you do want to actually delete it, you could simply run s3.deleteObject at the end of the function.

**Comment by jessica88888** [comment]
Dear Binoculars,

Thank you for all of your recommendations, helps and such a great function.

Best regards,
Jessica
