### ISSUE TITLE
GCP does not work with env variable config

### ISSUE THREAD

**Issue by tashian** [binoculars/aws-lambda-ffmpeg#39]
The dist/ files get packaged with references to process.env.* in them, which are not available inside of Cloud Functions.

I tried using the Babel plugin called transform-inline-environment-variables to inline the variables that are present at the time of transpiling. But that plugin is fragile: It doesn't handle destructuring assignment of envs into consts, and everything breaks if you reassign a process.env key.

**Comment by binoculars** [comment]
I've been delinquent on maintaining the GCF since it went to beta and have been focusing on AWS only. I'll have to get it working again for GCF and write better tests. I'm thinking about breaking it up into a separate repo though. Thoughts, feedback, and PRs welcome.
