### ISSUE TITLE
trying to restart the proccess 

### ISSUE THREAD

**Issue by merkinron** [binoculars/aws-lambda-ffmpeg#45]
hi,

i'm trying to restart my aws-lambda-ffmpeg. iv'e deleted the bucket it created on my s3 service on aws. when i recreate all the Environment Settings (with different bucket names) and then running 'gulp aws:default' i get the next error:
ValidationError: Stack:arn:aws:cloudformation:ap-southeast-2:384975490864:stack/aws-lambda-ffmpeg/8b422530-3ae1-11e7-8bc2-50fae94face6 is in ROLLBACK_COMPLETE state and can not be updated.

it also doesn't create a lambda function in the aws lambda service.
is there any way to delete everything and start from the begining? 

thanks :)

**Comment by merkinron** [comment]
it also doesn't create any lambda function at the lambda service as well

**Comment by GabrielStetco** [comment]
Hey @merkinron 
You need to remove also the cloudformation stack before running again gulp aws:default.
You can find it in the AWS services list, under Management Tools.

Regards
Gabriel

**Comment by merkinron** [comment]
@GabrielStetco thanks alot man it worked!
appreciate the quick response

**Comment by alvesl** [comment]
Hey, I have the same issue, but in my case the stack definitely does not exist: 

`An error occurred (ValidationError) when calling the DescribeStackEvents operation: Stack [aws-lambda-ffmpeg] does not exist`

Any ideas? Thanks!

**Comment by alvesl** [comment]
NVM! Wrong region, lol :)
