### ISSUE TITLE
Uploading a minute mp4 file fails to transcode

### ISSUE THREAD

**Issue by merkinron** [binoculars/aws-lambda-ffmpeg#46]
Hi, 

When i upload a short video the lambda transcode the input right away and everything seems to be working fine. but when i try to upload a one minute video it fails to transcode (the file size is 7Mb).
is there a reason it is happening?

ron

**Comment by binoculars** [comment]
Did you try changing the max duration? e.g.:
```sh
export VIDEO_MAX_DURATION='180'
```

**Comment by merkinron** [comment]
yes. my maxduration is 120.

**Comment by binoculars** [comment]
I'm not sure, maybe you can post the logs, what your current configuration is, and a sample video and I could try to look at it. Just need more detail. 7MB and one minute seam reasonable.

**Comment by merkinron** [comment]
<img width="1010" alt="env_vars" src="https://cloud.githubusercontent.com/assets/28754541/26158665/29e74a2e-3b25-11e7-92a5-318e3c02c907.png">
<img width="1191" alt="logs" src="https://cloud.githubusercontent.com/assets/28754541/26158664/29e144bc-3b25-11e7-99fc-dc3986a8206b.png">

**Comment by binoculars** [comment]
Looks like the Lambda function is timing out. Try changing [this line](https://github.com/binoculars/aws-lambda-ffmpeg/blob/a47fcd59c6684dbad0360ce023b85958c25220b5/platform/aws/cloudformation.json#L211) to a higher number. Current maximum is 300.

This should be configurable, so I'll label it as a bug.

**Comment by merkinron** [comment]
after changing the file i should just do the 'gulp aws:update' command?

**Comment by binoculars** [comment]
No, that just changes the Lambda itself. Since this is a change to the CFN template, you want `gulp aws:default`.

**Comment by merkinron** [comment]
so yes changing the timeout was the solution.
