### ISSUE TITLE
Run thumbnail only job

### ISSUE THREAD

**Issue by marcuslindblom** [binoculars/aws-lambda-ffmpeg#51]
Is it possible to run a thumbnail only job that outputs an image? I would like to run this command `ffmpeg -i file.mp4 -filter_complex "select='isnan(prev_selected_t)+gte(t-prev_selected_t\,1)',yadif,scale=240:-1, crop=240:135, tile=1x50" -vframes 1 -t 30 -q:v 4 scrub.jpg`. 

I have tried to to use the ffmpeg args like this `export FFMPEG_ARGS=$'-c:a copy -filter_complex "select=\'isnan(prev_selected_t)+gte(t-prev_selected_t\,1)\',yadif,scale=240:-1, crop=240:135, tile=1x50" -vframes 1 scrub.jpg'` but with no luck. I don't get any output at all?

**Comment by marcuslindblom** [comment]
Solved it and this is what I ended up with `-c:a copy -preset ultrafast -an -vcodec mjpeg -vf select=not(mod(n\,round($NB_FRAMES/50))),yadif,scale=240:135,tile=1x50 -q:v 5 -vframes 1 out.jpg`

I experience ffmpeg to be very slow when running as a lambda function. On my local machine the process takes a second on a very large file but when running as a lambda function it more like 30 seconds. @binoculars do you have any experience with ffmpeg being slow? Or maybe it's the the lambda architecture that makes things running slow?

**Comment by binoculars** [comment]
I'm glad you were able to find a solution. I usually test locally first and then try to use it in Lambda.

There are a couple of things that may make it appear slow. The function downloads the  file from S3, check it with FFprobe, runs it through FFmpeg, and then uploads it back to S3. So, the larger the file, the longer this will take.

Secondly, if you make a change to the Lambda function, it will take time to load the first time. Subsequent executions should be much faster when the container is warm. I believe after about 15 minutes to 1 hour, the container will hibernate, so you'll run into the cold start problem if you use it infrequently.

**Comment by marcuslindblom** [comment]
Ok, actually the download is takes only three seconds. I have also changed the parameters to ffprob so it run without frame count so that takes like 0 seconds for a 200Mb video. But then ffmpeg takes like a minute or more, until it times out or the disc space is empty. 🤔
