### ISSUE TITLE
Use existing bucket for source and destination?

### ISSUE THREAD

**Issue by marcuslindblom** [binoculars/aws-lambda-ffmpeg#52]
The `deployStack` task fails if the buckets exists. I would like to use an existing bucket, actually the same bucket for source and destination. Is it possible?

**Comment by binoculars** [comment]
It's possible, but not with the current code. You'd have to modify it to do that.

**Comment by marcuslindblom** [comment]
Ok, thanks!

**Comment by georgewritescode** [comment]
@marcuslindblom did you work out how to do this?

Thanks,
George``

**Comment by marcuslindblom** [comment]
@georgewritescode Sorry, I did not end up using lambda at all.
