### ISSUE TITLE
Adding a watermark to a video

### ISSUE THREAD

**Issue by lukeinage** [binoculars/aws-lambda-ffmpeg#61]
Is it possible to add a watermark to a video? Attempting this with these arguments is producing no output, but works fine locally:

-i 'watermark.png' -filter_complex 'overlay=10:10' -movflags +faststart -c:a copy out.mp4

I'm putting the watermark file in the root of the directory but no luck. I don't get an output from lambda when FFMPEG starts processing:

Valid video stream found. FFprobe finished.
Starting FFmpeg
Deleting /tmp/download
Duration: 259.24 ms	Billed Duration: 300 ms 	Memory Size: 1536 MB	Max Memory Used: 41 MB

**Comment by binoculars** [comment]
The current working directory for the FFmpeg command is the temp directory. If you provide the full file path, it should work. I believe it is /var/task/watermark.png but please verify that

**Comment by lukeinage** [comment]
Yes that was the issue, using the full path worked.

-i /var/task/watermark.png -filter_complex [0:v]scale='min(320\,iw):-2'[vid];[vid][1:v]overlay=W-w-10:H-h-10 -movflags +faststart -c:a copy out.mp4
