### ISSUE TITLE
error while running the package on trigger

### ISSUE THREAD

**Issue by hemant4sagoon** [binoculars/aws-lambda-ffmpeg#64]
Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

I am deploying the created zip to aws lambda function and when i am triggering it , then i am getting this error.

I am a complete new bie..
Just trying to run the code.

**Comment by tquiroga** [comment]
I've got the same, I can't manage to solve it...

**Comment by hemant4sagoon** [comment]
@tquiroga. you have to merge develop to master. It is not written but this bug was solved in the develop section

**Comment by binoculars** [comment]
👍 I'll have to do a release soon

**Comment by binoculars** [comment]
close via #69
