### ISSUE TITLE
Readme could be clearer.

### ISSUE THREAD

**Issue by potatowave** [binoculars/aws-lambda-ffmpeg#67]
Hi there, 

I'm admittedly a bit new when it comes to Lambda, but with this repo I'm left to make quite a few assumptions.  I realize that the Issues section should not be used for support, but I genuinely think the Readme could be a little more noob friendly, if only be including a few links to read up on certain parts of the process.

Some of these steps may have changed dramatically in the 8 months since the Readme was last updated, so if anyone is able to lend a hand I'd appreciate your guidance.  

In particular the Setup section, which left me guessing a few times.

1. Install node.js, preferably through nvm. Each platform service uses a specific version of Node.js.

_Install node.js where?  My assumption is on my local machine?  Or on the server instance?_

2. Clone this repo git clone ...

_If I carry the wrong assumption from #1, perhaps I'll clone it to some server instance._

3. Run npm install

_Okay, I've done that before. _

4. Create your function code's storage location (or choose an existing one)

_In this scenario I am using AWS Lambda.  Some more details on the config might be a little more handy here._

5. Update the platform-specific configuration JSON file (see below), and/or modify the code file for your purposes

_"the platform-specific configuration JSON file" What's the path to it?  Does one exist for AWS?_

6. Run Gulp (see below)

_This is the first project I've come across that uses Gulp, so a little explanation here would be nice too._

7. Invoke the function by uploading a video to your source storage location.

_A little reasoning about how/what is happening here would be great._

I wasn't able to successfully run the code with these steps.  For me I'm stick at running `sudo gulp aws:default` and getting the following error:

```[22:38:23] Starting 'download-ffmpeg'...
events.js:180
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'listener', 'Function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
    at _addListener (events.js:180:11)
    at WriteStream.addListener (events.js:240:10)
    at WriteStream.close (fs.js:2302:10)
    at WriteStream.file.on (/Users/mike/smashpotatoes/lambda-function/gulpfile.js:74:8)
    at WriteStream.emit (events.js:164:20)
    at finishMaybe (_stream_writable.js:605:14)
    at afterWrite (_stream_writable.js:456:3)
    at onwrite (_stream_writable.js:446:7)
    at fs.js:2246:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:703:5)```


Thanks in advance.

**Comment by binoculars** [comment]
Thanks for the feedback. I agree the README definitely could be updated and more clear. Unfortunately, I haven't been able to give this project the love it deserves lately. My day job has become my day-night-and-weekend job lately. I will put some effort into this repo when I have a bit more free time--hopefully around December. My priority so far has been to revamp the [ffmpeg build](https://github.com/binoculars/ffmpeg-build-lambda/), since that has been breaking with recent changes, and then I'll tackle this. If you want to make a pull request, I'll probably just merge it in.
