### ISSUE TITLE
simplified

### ISSUE THREAD

**Issue by trdavidson** [binoculars/aws-lambda-ffmpeg#7]
Hey! I have been studying this repository for a while now, and although it seems to do exactly what I am looking for, I am unable to figure out how to implement it. Especially the Gulp part is quite problematic, would you be able to please elaborate a little more in you tutorial? Thanks!

**Comment by binoculars** [comment]
Thanks for the feedback. I've been having issues with gulp myself--it usually wants to run things in parallel instead of in series. I've gotten it to package everything into a zip file, and have been going through AWS's web UI to upload the zip file and test the lambda function. Hang tight--I'll be working on this more over the weekend.

**Comment by trdavidson** [comment]
Awesome man - looking forward to seeing your work!

**Comment by binoculars** [comment]
Still thinking about this. I did a little work on it with b99059ff89c9467085a63ca75ae060035f9af77b, but it still needs more. I'll probably include a gulp task that creates the IAM execution role and policy. I haven't seen a lot of examples of this in JavaScript, so it might take a bit. All of the gulp tasks except for `upload` should work now.

**Comment by trdavidson** [comment]
Sorry for the late reply. I was wondering, wouldn't it be possible to use the AWS example docs, but instead of pulling the object just using the url to the object and using that with ffmpeg? something like this..: The only problem I have is how to pass a reference to the gm after taking the snapshot?

var async = require('async');
var AWS = require('aws-sdk');
var gm = require('gm')
            .subClass({ imageMagick: true }); // Enable ImageMagick integration.
var util = require('util');

// constants
var MAX_WIDTH  = 100;
var MAX_HEIGHT = 100;

// get reference to S3 client 
var s3 = new AWS.S3();
 
exports.handler = function(event, context) {
	// Read options from the event.
	console.log("Reading options from event:\n", util.inspect(event, {depth: 5}));
	var srcBucket = event.Records[0].s3.bucket.name;
	// Object key may have spaces or unicode non-ASCII characters.
    var srcKey    =
    decodeURIComponent(event.Records[0].s3.object.key.replace(/\+/g, " "));  
	var dstBucket = srcBucket + "resized";
	var dstKey    = "resized-" + srcKey;

	// Sanity check: validate that source and destination are different buckets.
	if (srcBucket == dstBucket) {
		console.error("Destination bucket must not match source bucket.");
		return;
	}

	// Infer the image type.
	var typeMatch = srcKey.match(/\.([^.]*)$/);
	if (!typeMatch) {
		console.error('unable to infer image type for key ' + srcKey);
		return;
	}
	var imageType = typeMatch[1];
	if (imageType != "jpg" && imageType != "png") {
		console.log('skipping non-image ' + srcKey);
		return;
	}

	// Download the image from S3, transform, and upload to a different S3 bucket.
	async.waterfall([
		function download(next) {
			// Download the image from S3 into a buffer.
			s3.getObjectUrl({
					Bucket: srcBucket,
					Key: srcKey
				},
				next);
			},
		function tranform('/path', next) {
			
ffmpeg('/path')
  .screenshots({
    timestamps: [1],
    filename: '/new_path', //not sure how to get a reference to pass to gm..
    size: '320x240'
  });

gm(reference.Body).size(function(err, size) {
				// Infer the scaling factor to avoid stretching the image unnaturally.
				var scalingFactor = Math.min(
					MAX_WIDTH / size.width,
					MAX_HEIGHT / size.height
				);
				var width  = scalingFactor * size.width;
				var height = scalingFactor * size.height;

				// Transform the image buffer in memory.
				this.resize(width, height)
					.toBuffer(imageType, function(err, buffer) {
						if (err) {
							next(err);
						} else {
							next(null, response.ContentType, buffer);
						}
					});
			});
		},
		function upload(contentType, data, next) {
			// Stream the transformed image to a different S3 bucket.
			s3.putObject({
					Bucket: dstBucket,
					Key: dstKey,
					Body: data,
					ContentType: contentType
				},
				next);
			}
		], function (err) {
			if (err) {
				console.error(
					'Unable to resize ' + srcBucket + '/' + srcKey +
					' and upload to ' + dstBucket + '/' + dstKey +
					' due to an error: ' + err
				);
			} else {
				console.log(
					'Successfully resized ' + srcBucket + '/' + srcKey +
					' and uploaded to ' + dstBucket + '/' + dstKey
				);
			}

			context.done();
		}
	);
};

**Comment by binoculars** [comment]
So you only want a sized thumbnail from a video (but not a resized video) that would get uploaded to S3?

**Comment by trdavidson** [comment]
Yes that would suffice for what I am working on right now

**Comment by binoculars** [comment]
I would skip `gm` altogether. FFmpeg can output the resized thumnail by itself. [This article](https://trac.ffmpeg.org/wiki/Scaling%20%28resizing%29%20with%20ffmpeg) should help.

```JavaScript
	child_process.execFile(
		'/tmp/ffmpeg',
		[
			'-y',
			'-loglevel', 'warning',
			'-i', '-',
			'-vf', 'thumbnail',
			'-vf', 'scale=100:-1',
			'-vframes', '1',
			'out.png'
		],
		{
			cwd: '/tmp',
			stdio: [null, null, null, 'pipe']
		}
	);
```

Then just read the file contents of `/tmp/out.png` into the s3 putObject body with `fs.readFileSync`.

**Comment by trdavidson** [comment]
I see! Allright thanks a lot, ill get going with this

On May 28, 2015, at 7:25 PM, Barrett Harber <notifications@github.com>
wrote:

I would skip gm altogether. FFmpeg can output the resized thumnail by
itself. This article
<https://trac.ffmpeg.org/wiki/Scaling%20%28resizing%29%20with%20ffmpeg>
should help.

    child_process.execFile(
        '/tmp/ffmpeg',
        [
            '-y',
            '-loglevel', 'warning',
            '-i', '-',
            '-vf', 'thumbnail',
            '-vf', 'scale=100:-1',
            '-vframes', '1',
            'out.png'
        ],
        {
            cwd: '/tmp',
            stdio: [null, null, null, 'pipe']
        }
    );

Then just read the file contents of /tmp/out.png into the s3 putObject body
with fs.readFileSync.

—
Reply to this email directly or view it on GitHub
<https://github.com/binoculars/aws-lambda-ffmpeg/issues/7#issuecomment-106626145>
.

**Comment by binoculars** [comment]
:ok: :cool: closing this out.
