### ISSUE TITLE
spawn ffmpeg stderr: [swscaler @ 0x30e40b0] No accelerated colorspace conversion found from yuv422p to rgb24.

### ISSUE THREAD

**Issue by Dsupreme** [binoculars/aws-lambda-ffmpeg#71]
Running the FFMpeg on AWS lamda as follows:

		const ff = spawn('ffmpeg', args, opts);

		ff.stdout.on('data', data => log('stdout: ', data));
		ff.stderr.on('data', data => {
			console.log(`ps stderr: ${data}`);
			read(outputDir);
			reject;
		});
		ff.on('close', (code) => {
			if (code !== 0) {
				console.log(`ps process exited with code ${code}`);
			}
			resolve;
		});

I receive the following error:

            ps stderr: [swscaler @ 0x30e40b0] No accelerated colorspace conversion found from yuv422p to rgb24.
            ps process exited with code null.

Args passed to FFMPEG function are:

             args:  [ '-y', '-loglevel', 'warning', '-i', '/tmp/download', '-ss', '00:00:5', '-vf', 'thumbnail,scale=320:240', '-frames:v', '1','abc.png' ]

Any tips / suggestions ?

**Comment by binoculars** [comment]
Hard to say. Does it work when you run FFmpeg locally on the same file? I'm guessing that FFmpeg doesn't recognize that particular format.

**Comment by Dsupreme** [comment]
It's an (13.4MB) mp4 file. 
And yes the FFmpeg command runs fine locally

**Comment by Dsupreme** [comment]
I removed arguments (-loglevel) and ran the lambda function. Here are the logs.

    2017-11-30T06:47:59.321Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	args: [ '-y',
    '-i',
    '/tmp/download',
    '-ss',
    '00:00:5',
    '-vf',
    'thumbnail,scale=320:240',
    '-frames:v',
    '1',
    'lg.png' ]
    2017-11-30T06:48:00.342Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: ffmpeg version N-87772-g217a723b4e Copyright (c) 2000-2017 the FFmpeg developers
    built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
    configuration: --prefix=/home/travis/ffmpeg_build --pkg-config-flags=--static --extra-cflags='-I/home/travis/ffmpeg_build/include -static' --extra-ldflags='-L/home/travis/ffmpeg_build/lib -static' --bindir=/home/travis/bin --cc='gcc -m64' --cpu=sandybridge --arch=x84_64 --disable-shared --enable-static --disable-debug --disable-runtime-cpudetect --disable-ffplay --disable-ffserver --disable-doc --disable-network --disable-devices --disable-protocols --enable-protocol=file --enable-protocol=pipe --enable-protocol=tee --enable-libmp3lame --enable-libvpx --enable-libwebp --enable-libopus --enable-fontconfig --enable-gray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libspeex --enable-libtheora --enable-libvorbis --enable-gpl --enable-frei0r --enable-libx264 --enable-libx265 --enable-libxvid --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc

    2017-11-30T06:48:00.440Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: libavutil 55. 77.101 / 55. 77.101
    libavcodec 57.106.104 / 57.106.104
    libavformat 57. 82.104 / 57. 82.104
    libavdevice 57. 9.102 / 57. 9.102
    libavfilter 6.106.101 / 6.106.101
    libswscale 4. 7.103 / 4. 7.103
    libswresample 2. 8.100 / 2. 8.100
    libpostproc 54. 6.100 / 54. 6.100

    2017-11-30T06:48:01.260Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/download':
    Metadata:
    major_brand : isom
    minor_version : 512
    compatible_brands: isomiso2avc1mp41
    encoder : Lavf56.40.101
    Duration: 00:00:50.02, start: 0.000000, bitrate: 2335 kb/s

    2017-11-30T06:48:01.261Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: Stream #0:0(eng): Video: h264 (High 4:2:2) (avc1 / 0x31637661), yuv422p, 1920x1080 [SAR 1:1 DAR 16:9], 1946 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
    handler_name : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 384 kb/s (default)
    Metadata:
    handler_name : SoundHandler

    2017-11-30T06:48:01.280Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: Stream mapping:

    2017-11-30T06:48:01.399Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: Stream #0:0 -> #0:0 (h264 (native) -> png (native))
    Press [q] to stop, [?] for help

    2017-11-30T06:48:02.039Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: frame= 0 fps=0.0 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A 
    2017-11-30T06:48:02.501Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: [swscaler @ 0x32c2840] No accelerated colorspace conversion found from yuv422p to rgb24.

    2017-11-30T06:48:02.760Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: Output #0, image2, to 'lg.png':
    Metadata:
    major_brand : isom
    minor_version : 512
    compatible_brands: isomiso2avc1mp41
    encoder : Lavf57.82.104

    2017-11-30T06:48:02.780Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: Stream #0:0(eng): Video: png, rgb24, 320x240 [SAR 4:3 DAR 16:9], q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc (default)
    Metadata:
    handler_name : VideoHandler
    encoder : Lavc57.106.104 png

    2017-11-30T06:48:02.939Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: frame= 0 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed= 0x 
    2017-11-30T06:48:04.300Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: frame= 0 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed= 0x 
    2017-11-30T06:48:04.620Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps stderr: frame= 0 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed= 0x 
          2017-11-30T06:48:27.702Z	640e5500-d59a-11e7-bfdc-136ca9bae63b	ps process exited with 
          code null
          END RequestId: 640e5500-d59a-11e7-bfdc-136ca9bae63b

**Comment by binoculars** [comment]
🤷‍♂️ Not sure. Without the video and full code you're running, which doesn't look like mine, I can't tell you what it's doing. 

I don't see a promise here, but in the log it has `ps process exited with code null` and you're saying `code !== 0`

```js
       ff.on('close', (code) => {
		if (code !== 0) {
			console.log(`ps process exited with code ${code}`);
		}
		resolve;
	});
```

**Comment by Dsupreme** [comment]
Below is the ffmpeg function:

    function ffmpeg(keyPrefix) {
	  log('Starting FFmpeg');
	  log(keyPrefix.replace('/video/', ''));                    // For matching sub folders in s3
	  var filenamethumbnail = keyPrefix.replace('/video/', ''); // For matching sub folders in s3

	  return new Promise((resolve, reject) => {
		const args = [
			'-y',
			//'-loglevel', 'warning',
			'-i', download,
			'-ss', '00:00:5',
			...FFMPEG_ARGS
				.replace('$KEY_PREFIX', filenamethumbnail)
				.split(' ')
		];

		console.log('args: ', args);

		const opts = {
			cwd: outputDir
		};

		const ff = spawn('ffmpeg', args, opts);
		// .on('message', msg => log(msg))
		// .on('error', reject)
		// .on('data', (data) => { console.log(data) })
		// .on('close', resolve);

		ff.stdout.on('data', data => log('stdout: ', data));
		ff.stderr.on('data', data => {
			console.log(`ps stderr: ${data}`);
			read(outputDir);
			reject;
		});
		ff.on('close', (code) => {
			if (code !== 0) {
				console.log(`ps process exited with code ${code}`);
			}
			resolve;
		});
	});
    }

**Comment by Dsupreme** [comment]
Well i found a mistake, i had commented out ffprobe() function.

But now i am receiving another error of 

FFprobe: no valid video stream found

Stdout logs the following

```
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High 4:2:2",
            "codec_type": "video",
            "codec_time_base": "1/50",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 1920,
            "height": 1080,
            "coded_width": 1920,
            "coded_height": 1080,
            "has_b_frames": 2,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv422p",
            "level": 40,
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "25/1",
            "avg_frame_rate": "25/1",
            "time_base": "1/12800",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 640000,
            "duration": "50.000000",
            "bit_rate": "1946032",
            "bits_per_raw_sample": "8",
            "nb_frames": "1250",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "handler_name": "VideoHandler"
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "mp4a",
            "codec_tag": "0x6134706d",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/48000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 2400000,
            "duration": "50.000000",
            "bit_rate": "384487",
            "max_bit_rate": "384487",
            "nb_frames": "2345",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "handler_name": "SoundHandler"
            }
        }
    ],
    "format": {
        "filename": "download",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "50.022000",
        "size": "14604772",
        "bit_rate": "2335735",
        "probe_score": 100,
        "tags": {
            "major_brand": "isom",
            "minor_version": "512",
            "compatible_brands": "isomiso2avc1mp41",
            "encoder": "Lavf56.40.101"
        }
    }
}
```

**Comment by binoculars** [comment]
if you have a 50-second video and `export VIDEO_MAX_DURATION='30'`, you're gonna have a bad time

**Comment by Dsupreme** [comment]
Okay. I got the whole thing to work.

Below are the environment variables i used in lambda

```
FFMPEG_ARGS:
-c:a copy -movflags +faststart -vf thumbnail -vf scale='min(320\,iw):-2' -vframes 1 $KEY_PREFIX.png

MIME_TYPES:
{"png":"image/png","mp4":"video/mp4"}

USE_GZIP:
false
```
I had to disable ffprobe()

My ffmpeg function was as follows

```javascript
function ffmpeg(keyPrefix) {
	log('Starting FFmpeg');
	log(keyPrefix.replace('video/', ''));
	var filenamethumbnail = keyPrefix.replace('video/', '');

	return new Promise((resolve, reject) => {
		const args = [
			'-y',
			'-loglevel', 'warning',
			'-i', download,
			'-ss', '00:00:5',
			...FFMPEG_ARGS
				.replace('$KEY_PREFIX', filenamethumbnail)
				.split(' ')
		];

		console.log('args: ', args);

		const opts = {
			cwd: outputDir
		};

		const ff = spawn('ffmpeg', args, opts);
		// .on('message', msg => log(msg))
		// .on('error', reject)
		// .on('data', (data) => { console.log(data) })
		// .on('close', resolve);

		ff.stdout.on('data', data => {
			log('stdout: ', data);
			resolve();
		});
		ff.stderr.on('data', data => {
			console.log(`ps stderr: ${data}`);
			reject();
		});
		ff.on('close', (code) => {
			if (code !== 0) {
				console.log(`ps process exited with code ${code}`);
			}
			log('closed');
			resolve();
		});
	});
}
```
