### ISSUE TITLE
Unable to import module 'aws/index': Error (v3.2.0)

### ISSUE THREAD

**Issue by amitport** [binoculars/aws-lambda-ffmpeg#72]
just started using a clean version v3.2.0 
when running the lambda on AWS I'm getting this error

(does not seem related to https://github.com/binoculars/aws-lambda-ffmpeg/issues/21)

**Comment by amitport** [comment]
OK, after a couple of hours wasted, it seems that lambda has issues with the 'aws' folder name. Renaming 'aws' folder to 'somethingelse' and changing the handler to 'somethingelse/index.handler' seems to work.

**Comment by binoculars** [comment]
The end-to-end tests passed here: https://travis-ci.org/binoculars/aws-lambda-ffmpeg/builds/307774388

**Comment by tseruga** [comment]
Same error on my end. Renaming folder and handler did not fix issue.

**Comment by binoculars** [comment]
Can you please provide steps to reproduce and fix the error?

Travis deploys the function to AWS Lambda and invokes it for the tests to pass, so I don't know how this error is happening. Logs, OS details, and the command you're running would be useful.

**Comment by amitport** [comment]
@binoculars, sorry, I'm not using this lib anymore and don't remember the exact details. I was basically just following the minimal Lambda setup when I got `Unable to import module 'aws/index': Error` from AWS lambda log. Changing `aws` folder name helped. (it seems like this is may be an AWS Lambda bug)

**Comment by binoculars** [comment]
Ok I'm going to close this issue--perhaps reporting the bug to AWS would be good if anyone runs into it in the future. I'd need to see it on my own account to accurately report it to them. Thanks and good luck.
