### ISSUE TITLE
Question: gif to mp4

### ISSUE THREAD

**Issue by cashmash** [binoculars/aws-lambda-ffmpeg#73]
I was able to run the whole stack. Thanks for that.

In order to use a different ffmpeg command I understand that I have to modify (an incoming gif shall be transformed to mp4):

`export FFMPEG_ARGS` and I would edit `MIME_TYPES` 

Am I correct or wrong?

(terminal command to transform gif to mp4):
```ffmpeg -i image.gif -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" video.mp4```

I uncommented `FFprobe` for now, how would you define `FFMPEG_ARGS` to accomplish this? somehow my mp4s that get created are 0 bytes meaning something is wrong

**Comment by binoculars** [comment]
`MIME_TYPES` only really matters for when you want to upload them to S3 so it sets the proper mime type for the output file

Setting `FFMPEG_ARGS` to
`-movflags faststart -pix_fmt yuv420p -vf scale='trunc(iw/2)*2:trunc(ih/2)*2' out.mp4` should work. Usually it's a problem around escaping quotes or something like that with the scale parameter.

**Comment by cashmash** [comment]
thx @binoculars I had double quotes
