### ISSUE TITLE
Google Cloud Functions lacks runtime environment variables

### ISSUE THREAD

**Issue by dlackty** [binoculars/aws-lambda-ffmpeg#78]
Correct me if I'm wrong, but after #20, which move config values to environment variables, usage of this project on Google Cloud Functions became unusable because CF doesn't provide runtime env variable configuration.

My suggestion is to introduce [babel-plugin-transform-inline-environment-variables](https://babeljs.io/docs/plugins/transform-inline-environment-variables/) during the build process for GCP. How do you think?

**Comment by binoculars** [comment]
I haven't tested GCP since it moved to beta. We could probably just merge the properties of process.env and a config.json file (if it exists) with the object spread operator and that would be better than adding another dependency.

**Comment by cdgraff** [comment]
Currently GCF support Environments Variables, see the doc: https://cloud.google.com/functions/docs/env-var

**Comment by dlackty** [comment]
@cdgraff That's correct. Gonna resolve this issue.
