### ISSUE TITLE
No need for ffmpeg filesystem operations

### ISSUE THREAD

**Issue by edjames** [binoculars/aws-lambda-ffmpeg#8]
Hi

Thanks for this repo - it's proven to be very useful for me.

I did find one problem though, which was the need to copy the ffmpeg binaries to the `/tmp` directory. I was running into problems because this step had to be performed synchronously so that the binaries were actually available prior to executing them.

As it turns out, you don't actually need to do this at all. All you need to do is update the `PATH` variable at the start of your function and the binaries are immediately available. Just do this:

    process.env[‘PATH’] = process.env[‘PATH’] + ‘:’ + process.env[‘LAMBDA_TASK_ROOT’]

More info here: https://aws.amazon.com/blogs/compute/running-executables-in-aws-lambda/

Thanks,
Ed.

**Comment by binoculars** [comment]
Awesome. Thanks for the tip! I'm glad that there's a much more elegant solution for this.
