### ISSUE TITLE
Video less than 30 mins is timed out on AWS lambda

### ISSUE THREAD

**Issue by hammadhasandogar** [binoculars/aws-lambda-ffmpeg#87]

**Comment by hammadhasandogar** [comment]
Should I look for specific video size check instead of video duration?

**Comment by binoculars** [comment]
30 minutes is definitely a longer video than I would anticipate being able to convert inside of Lambda's 5 minute window. There are strategies for that, but I'd recommend for longer videos like this you either run it as a container or use elastic transcoder.

**Comment by hammadhasandogar** [comment]
Thanks for your reply.
Since lambda offered 15 mins execution now, so I am processing 30 mins video on Lambda and more than that on EC2 using ffmpeg binaries .

**Comment by Snipsnoop** [comment]
Why not use https://aws.amazon.com/mediaconvert/ ?

**Comment by hammadhasandogar** [comment]
because its very expense as compared to lambda solution, EC2 will be used for one hour only in a day, to batch process all videos.
