### ISSUE TITLE
Help implementing this build

### ISSUE THREAD

**Issue by jimdur8n** [binoculars/aws-lambda-ffmpeg#91]
Hi @binoculars, Would you be interested in a consulting gig to implement this build on AWS for my institution? If so, could you PM me on twitter: @jimdur8n? Thanks!

**Comment by binoculars** [comment]
Hey Jim. I’m really pressed for time, so unfortunately I can’t commit to any consulting gigs. If you want to use it, I’d be happy to share any thoughts with you over the phone/video chat if you like.

**Comment by jimdur8n** [comment]
Hi Barrett, thank you for letting us know. And thanks for your work on this aws-ffmpeg, it looks promising!
